### ISSUE TITLE
no version available anymore

### ISSUE THREAD

**Issue by wotography** [HeIIow2/music-downloader#18]
pycountry
```
ERROR: Could not find a version that satisfies the requirement pycountry~=24.0.1 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.14, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.14.7, 0.14.8, 0.15, 0.16, 0.17, 0.18, 0.19, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 16.10.23rc1, 16.10.23rc2, 16.10.23rc3, 16.11.8, 16.11.27, 16.11.27.1, 17.1.2, 17.1.8, 17.5.14, 17.9.23, 18.2.23, 18.5.20, 18.5.26, 18.12.8, 19.7.15, 19.8.18, 20.7.2, 20.7.3, 22.1.10, 22.3.5, 23.12.7, 23.12.11, 24.6.1)
ERROR: No matching distribution found for pycountry~=24.0.1
```

pyffmpeg:
```
ERROR: Could not find a version that satisfies the requirement pyffmpeg~=2.4.2.18 (from versions: 1.0.0-windows, 1.4, 1.4.1, 1.5, 1.6, 1.6.1, 1.7.0, 1.7.1, 1.7.2, 1.8, 1.8.1, 2.0, 2.0.1, 2.0.2a0, 2.0.2, 2.0.3, 2.0.4, 2.0.5.1, 2.1.0, 2.2.0.1, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.4.1, 2.2.4.3, 2.3, 2.3.0.1b2, 2.3.0.2, 2.3.0.3, 2.4, 2.4.1, 2.4.2.10, 2.4.2.11, 2.4.2.12, 2.4.2.13, 2.4.2.14, 2.4.2.15)
ERROR: No matching distribution found for pyffmpeg~=2.4.2.18
```

**Comment by HeIIow2** [comment]
Hi, I changed repositories to this git page. https://gitea.elara.ws/music-kraken/music-kraken-core

You would only need to change the versions in pyproject.toml. Feel free to make a PR and/or open a pr for this on this plattform. I will update this readme tomorrow.

**Comment by wotography** [comment]
i am running this from your instructions:
'python3 -m pip install -r requirements.txt'
will wait for your update of readme. thanks!

**Comment by HeIIow2** [comment]
hi I will get to updating the readme here soon. For the meantime here is the pypi package with an up to date readme, which you can just install

https://pypi.org/project/music-kraken/

Beware that youtube changed lots of stuff so it could be the case that parts of my programm broke, I'll update youtube dl soon. I unfortunately have very limited time.
