### ISSUE TITLE
unable to run its on Arch (WSL2 win11)

### ISSUE THREAD

**Issue by hrdkmishra** [HeIIow2/music-downloader#2]
![image](https://user-images.githubusercontent.com/87580981/203259793-aae6c977-6827-4cb5-80fa-6f406ac9673b.png)

im using WSL2 on Win11. 
maybe im doing something wrong :(

**Comment by HeIIow2** [comment]
I'll look into it if I find time, but most likely this aint an issue on my end.
Pip adds it to the PATH with `entry_points={'console_scripts': ['music-kraken = music_kraken:cli']}` in setup.py. So you could try search for "WSL2 pip entry_ponts console_scripts not working". This might help you https://stackoverflow.com/questions/42182707/pip-not-installing-entry-points-as-executables but no garantee. If you manage to find the fix and I can fix it in setup.py I will change it.

Good luck :3

**Comment by wereii** [comment]
Most probably you don't have `~/.local/bin` in your `PATH` @hrdkmishra

**Comment by ghost** [comment]
> Most probably you don't have `~/.local/bin` in your `PATH` @hrdkmishra

Adding this line to your `config.fish` will fix the problem
```fish
set -gx PATH ~/.local/bin $PATH
```

**Comment by wereii** [comment]
@HeIIow2 I am pretty sure he meant @hrdkmishra. 
Fish is a kind of linux shell, this has nothing to do with python packaging.

**Comment by HeIIow2** [comment]
@wereii Ok thank you <33

**Comment by HeIIow2** [comment]
@hrdkmishra can you please give feedback on if it worked?

**Comment by hrdkmishra** [comment]
> @hrdkmishra can you please give feedback on if it worked? 

Yes it worked thanks a lot @abhigyanmadhukalya @HeIIow2 @wereii

**Comment by HeIIow2** [comment]
@hrdkmishra thanks for the reply. That's great next time please close the issue once your problems are resolved or comment they are :)
