### ISSUE TITLE
windows - cant find music directory

### ISSUE THREAD

**Issue by aatifurrahman** [HeIIow2/music-downloader#4]
It cant determine the Music Directory '/Music'. but finds it after '\Music'.

May be create directory separately after CDing to %home%.

**Comment by HeIIow2** [comment]
Hey, thanks for raising the issue.
Can you try to running `os.path.join(os.path.expanduser("~"), "Music")`. Tell me if it finds the music directory  on windows.

**Comment by aatifurrahman** [comment]
yes it works.

**Comment by HeIIow2** [comment]
Perfect. I have a fix, which will be published by the next update.
The update is pretty much finished, but I need to test it a bit. If you are on windows and have this issue, you can
install a probaply pretty stable version with the fix like this:

`python3 -m pip install -i https://test.pypi.org/simple/ music-kraken==1.1.3 -U`  
`pip install -i https://test.pypi.org/simple/ music-kraken==1.1.3 -U`

If this doesn't work open a new issue. Have Fun :)
