### ISSUE TITLE
Cannot find the "Music" directory on localized non-english systems

### ISSUE THREAD

**Issue by DistantThunder** [HeIIow2/music-downloader#7]
Hi,

On non-english systems, the program immediately crashes as it can't find the hardcoded "~/Music" directory.

> FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/Music'

Patch proposal: https://github.com/HeIIow2/music-downloader/pull/6

**Comment by HeIIow2** [comment]
Hey thank you very much <33 I appreciate you're work really much, I'd appreciate if you update you're pull request according to my comment. :)

**Comment by HeIIow2** [comment]
<333
