### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by shivanshu-semwal** [HeIIow2/music-downloader#8]
<https://github.com/HeIIow2/music-downloader/blob/693d04800af6e182caac9594e196c0b62041ecd9/README.md?plain=1#L335>

It should be, `https://musicbrainz.org/`, otherwise <https://github.com/HeIIow2/music-downloader/blob/693d04800af6e182caac9594e196c0b62041ecd9/README.md?plain=1#L241> this links open incorrectly as - <https://github.com/HeIIow2/music-downloader/blob/master/musicbrainz.org>.

**Comment by HeIIow2** [comment]
Thank you for noticing and opening an issue.
It schould be fixed now. If not open a new issue <33
